- block:
    # Get all the running VMs related to a storage domain and shut them down
    - name: Fetch VMs in the storage domain
      ovirt_vm_facts:
          pattern: >
            status != down and
            storage.name={{ storage['dr_' + dr_source_map + '_name'] }} and
            datacenter={{ storage['dr_' + dr_source_map + '_dc_name'] }}
          auth: "{{ ovirt_auth }}"

    # TODO: Add a wait until the VM is really down
    - name: Shutdown VMs
      include_tasks: tasks/clean/shutdown_vm.yml
      vars:
          vms: "{{ item }}"
      with_items: "{{ ovirt_vms }}"
  ignore_errors: "{{ dr_ignore_error_clean }}"
  tags:
      - fail_back
      - clean_engine
